# fastapi-api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: exam-2-jazi-yacine 
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-jazi-yacine-exam 
  template:
    metadata:
      labels:
      workload.user.cattle.io/workloadselector: apps.deployment-jazi-yacine-exam 
    spec:
      containers:
        - image: ghcr.io/yacinejazi/2021-2022-mlops-exam-2-yacinejazi:master
          imagePullPolicy: Always
          name: api-container
          ports:
          - containerPort: 80
           # name: 80tcp
           # protocol: TCP
           # _serviceType: ClusterIP
      nodeName: jazi-yacine
---
apiVersion: v1
kind: Service
metadata:
  name: svc-storage-api
  namespace: exam-fast-api # Change to your own namespace!
spec:
  selector:
      workload.user.cattle.io/workloadselector: apps.deployment-jazi-yacine-exam 
  ports:
    - name: fastapi-http
      port: http
      targetPort: 80
      protocol: TCP 
  type: LoadBalancer